### ISSUE TITLE
External SVGs in SCSS are not handled correctly for production mode

### ISSUE THREAD

**Issue by akrigline** [RobotsAndPencils/react-gantry#33]
External background Image SVG files are not handled correctly by webpack.

```css
.cancel {
  background: url("/src/assets/svg/cancel.svg?external");
}
```
This doesn't get copied over in dist.
